on:
  push:
    branches:
      - MK3S-remake

name: Build the firmware and create a release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Execute the build script
        run: ./build.sh
      - name: Rename compiled binary
        run: mv ../Prusa-Firmware-build/Firmware.ino.hex ./PrusaRemake_1_75mm_MK3S_EINSy10a_E3DV6Clone-firmware-${{ steps.slug.outputs.sha8 }}.hex  
      - uses: actions/upload-artifact@v2
        with:
          name: firmware-${{ steps.slug.outputs.sha8 }}
          path: ./PrusaRemake_1_75mm_MK3S_EINSy10a_E3DV6Clone-firmware-${{ steps.slug.outputs.sha8 }}.hex
    outputs:
      firmware_artifact: firmware-${{ steps.slug.outputs.sha8 }}
      firmware_file_name: PrusaRemake_1_75mm_MK3S_EINSy10a_E3DV6Clone-firmware-${{ steps.slug.outputs.sha8 }}.hex
        
  create_release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ steps.slug.outputs.sha8 }}
          release_name: Prusa MK3S Remake firmware ${{ steps.slug.outputs.sha8 }}
          body: |
            This is an automated build with the latest firmware code changes, built ${{ steps.date.outputs.date }} from the ${{ github.ref }} branch.
            
            Visit the [releases page](https://github.com/prusa3d/Prusa-Firmware/releases) of the official firmware for a changelog.
          draft: false
          prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      
  
  publish_binary:
    name: Publish compiled binary
    needs: [build, create_release]
    runs-on: ubuntu-latest
    steps:
      - name: Download built firmware
        uses: actions/download-artifact@v1
        with:
          name: ${{ jobs.build.outputs.firmware_artifact }}
      - name: Upload release asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ jobs.create_release.outputs.upload_url }} 
          asset_path: ./${{ jobs.build.outputs.firmware_artifact }}/${{ jobs.build.outputs.firmware_file_name }}
          asset_name: ${{ jobs.build.outputs.firmware_file_name }}
          asset_content_type: application/x-binary
