on:
  push:
    branches:
      - MK3S-remake

name: Build and create a release

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Execute the build script
        run: ./build.sh
      - name: Debug output
        run: ls -lah
        
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Get short SHA
        id: slug
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Prusa MK3S Remake firmware ${{ steps.slug.outputs.sha8 }}
          body: |
            This is an automated build with the latest firmware code changes, built ${{ steps.date.outputs.date }} from the ${{ github.ref }} branch.
            
            Visit the [releases page](https://github.com/prusa3d/Prusa-Firmware/releases) of the official firmware for a changelog.
          draft: false
          prerelease: false
